version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_system
    ports:
      - "3308:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    platform: linux/amd64  
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysqldata: {}